name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

env:
  VCPKG_INSTALLED_DIR: ${{ github.workspace }}/vcpkg/installed

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Check format
        run: clang-format --dry-run --Werror src/*.cpp include/janus/*.hpp tests/*.cpp

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: xmake-io/github-action-setup-xmake@3a1a5dddfc7fa625d9a698738334bf55655a861a
        with:
          xmake-version: 3.1.1
      - uses: lukka/run-vcpkg@b1a0dd252f06b9e25b3c022a9a03bd7a427fb6a2 # v11
        with:
          vcpkgJsonGlob: vcpkg.json
          vcpkgGitCommitId: 04a9d8e5212d01ee1dd9478eadd9caade4f8b0d4
          runVcpkgInstall: true
          doNotCache: false
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ~/.xmake/cache
          key: xmake-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('xmake.lua', 'vcpkg.json') }}
      - name: Build
        run: xmake f -m release -y && xmake
      - name: Test
        run: xmake test
